### ISSUE TITLE
Final callback occurs before SVG(s) appear in DOM

### ISSUE THREAD

**Issue by jonasjancarik** [iconic/SVGInjector#60]
I want to apply another jQuery plugin to all the inlined SVGs using the final callback rather than the 'each' callback, but at the point when the callback is called, the `<svg>` tags are not yet actually present in the DOM (or in other words the SVGs are not yet inlined).

This is what my callback looks like:

![image](https://user-images.githubusercontent.com/2459191/42286258-8f131f40-7fb2-11e8-8249-d2ed1dfaf189.png)

And this is the DOM at the moment the breakpoint occurs - note these are `<img>` tags:

![image](https://user-images.githubusercontent.com/2459191/42286040-c7448ca6-7fb1-11e8-8ffe-94e29010e328.png)

**Comment by theRealPadster** [comment]
You've probably got it solved, but I just figured I'd post this in case anyone comes across it in the future.
It looks like you're running the function `applyAnotherPlugin` instead of passing the function definition. When you use the parenthesis, it executes it whereas you just want it to pass the function. So what you want is: 

```
SVGInjector(SvgsToInline, {
  each: function(svg) {
    $(svg).addClass('svg-to-process')
  }
}, applyAnotherPlugin);
```
